export interface ItemTemplate {
  entry: number;
  class: number;
  subclass: number;
  unk0: number;
  name: string;
  displayid: number;
  Quality: number;
  Flags: number;
  BuyCount: number;
  BuyPrice: number;
  SellPrice: number;
  InventoryType: number;
  AllowableClass: number;
  AllowableRace: number;
  ItemLevel: number;
  RequiredLevel: number;
  RequiredSkill: number;
  RequiredSkillRank: number;
  requiredspell: number;
  requiredhonorrank: number;
  RequiredCityRank: number;
  RequiredReputationFaction: number;
  RequiredReputationRank: number;
  maxcount: number;
  stackable: number;
  ContainerSlots: number;
  stat_type1: number;
  stat_value1: number;
  stat_type2: number;
  stat_value2: number;
  stat_type3: number;
  stat_value3: number;
  stat_type4: number;
  stat_value4: number;
  stat_type5: number;
  stat_value5: number;
  stat_type6: number;
  stat_value6: number;
  stat_type7: number;
  stat_value7: number;
  stat_type8: number;
  stat_value8: number;
  stat_type9: number;
  stat_value9: number;
  stat_type10: number;
  stat_value10: number;
  dmg_min1: number;
  dmg_max1: number;
  dmg_type1: number;
  dmg_min2: number;
  dmg_max2: number;
  dmg_type2: number;
  dmg_min3: number;
  dmg_max3: number;
  dmg_type3: number;
  dmg_min4: number;
  dmg_max4: number;
  dmg_type4: number;
  dmg_min5: number;
  dmg_max5: number;
  dmg_type5: number;
  armor: number;
  holy_res: number;
  fire_res: number;
  nature_res: number;
  frost_res: number;
  shadow_res: number;
  arcane_res: number;
  delay: number;
  ammo_type: number;
  RangedModRange: number;
  spellid_1: number;
  spelltrigger_1: number;
  spellcharges_1: number;
  spellppmRate_1: number;
  spellcooldown_1: number;
  spellcategory_1: number;
  spellcategorycooldown_1: number;
  spellid_2: number;
  spelltrigger_2: number;
  spellcharges_2: number;
  spellppmRate_2: number;
  spellcooldown_2: number;
  spellcategory_2: number;
  spellcategorycooldown_2: number;
  spellid_3: number;
  spelltrigger_3: number;
  spellcharges_3: number;
  spellppmRate_3: number;
  spellcooldown_3: number;
  spellcategory_3: number;
  spellcategorycooldown_3: number;
  spellid_4: number;
  spelltrigger_4: number;
  spellcharges_4: number;
  spellppmRate_4: number;
  spellcooldown_4: number;
  spellcategory_4: number;
  spellcategorycooldown_4: number;
  spellid_5: number;
  spelltrigger_5: number;
  spellcharges_5: number;
  spellppmRate_5: number;
  spellcooldown_5: number;
  spellcategory_5: number;
  spellcategorycooldown_5: number;
  bonding: number;
  description: string;
  PageText: number;
  LanguageID: number;
  PageMaterial: number;
  startquest: number;
  lockid: number;
  Material: number;
  sheath: number;
  RandomProperty: number;
  RandomSuffix: number;
  block: number;
  itemset: number;
  MaxDurability: number;
  area: number;
  Map: number;
  BagFamily: number;
  TotemCategory: number;
  socketColor_1: number;
  socketContent_1: number;
  socketColor_2: number;
  socketContent_2: number;
  socketColor_3: number;
  socketContent_3: number;
  socketBonus: number;
  GemProperties: number;
  RequiredDisenchantSkill: number;
  ArmorDamageModifier: number;
  ScriptName: string;
  DisenchantID: number;
  FoodType: number;
  minMoneyLoot: number;
  maxMoneyLoot: number;
  Duration: number;
  ExtraFlags: number;
}

export const defaultItemTemplate: ItemTemplate = {
  entry: 0,
  class: 0,
  subclass: 0,
  unk0: -1,
  name: '',
  displayid: 0,
  Quality: 0,
  Flags: 0,
  BuyCount: 1,
  BuyPrice: 0,
  SellPrice: 0,
  InventoryType: 0,
  AllowableClass: -1,
  AllowableRace: -1,
  ItemLevel: 0,
  RequiredLevel: 0,
  RequiredSkill: 0,
  RequiredSkillRank: 0,
  requiredspell: 0,
  requiredhonorrank: 0,
  RequiredCityRank: 0,
  RequiredReputationFaction: 0,
  RequiredReputationRank: 0,
  maxcount: 0,
  stackable: 1,
  ContainerSlots: 0,
  stat_type1: 0,
  stat_value1: 0,
  stat_type2: 0,
  stat_value2: 0,
  stat_type3: 0,
  stat_value3: 0,
  stat_type4: 0,
  stat_value4: 0,
  stat_type5: 0,
  stat_value5: 0,
  stat_type6: 0,
  stat_value6: 0,
  stat_type7: 0,
  stat_value7: 0,
  stat_type8: 0,
  stat_value8: 0,
  stat_type9: 0,
  stat_value9: 0,
  stat_type10: 0,
  stat_value10: 0,
  dmg_min1: 0,
  dmg_max1: 0,
  dmg_type1: 0,
  dmg_min2: 0,
  dmg_max2: 0,
  dmg_type2: 0,
  dmg_min3: 0,
  dmg_max3: 0,
  dmg_type3: 0,
  dmg_min4: 0,
  dmg_max4: 0,
  dmg_type4: 0,
  dmg_min5: 0,
  dmg_max5: 0,
  dmg_type5: 0,
  armor: 0,
  holy_res: 0,
  fire_res: 0,
  nature_res: 0,
  frost_res: 0,
  shadow_res: 0,
  arcane_res: 0,
  delay: 1000,
  ammo_type: 0,
  RangedModRange: 0,
  spellid_1: 0,
  spelltrigger_1: 0,
  spellcharges_1: 0,
  spellppmRate_1: 0,
  spellcooldown_1: -1,
  spellcategory_1: 0,
  spellcategorycooldown_1: -1,
  spellid_2: 0,
  spelltrigger_2: 0,
  spellcharges_2: 0,
  spellppmRate_2: 0,
  spellcooldown_2: -1,
  spellcategory_2: 0,
  spellcategorycooldown_2: -1,
  spellid_3: 0,
  spelltrigger_3: 0,
  spellcharges_3: 0,
  spellppmRate_3: 0,
  spellcooldown_3: -1,
  spellcategory_3: 0,
  spellcategorycooldown_3: -1,
  spellid_4: 0,
  spelltrigger_4: 0,
  spellcharges_4: 0,
  spellppmRate_4: 0,
  spellcooldown_4: -1,
  spellcategory_4: 0,
  spellcategorycooldown_4: -1,
  spellid_5: 0,
  spelltrigger_5: 0,
  spellcharges_5: 0,
  spellppmRate_5: 0,
  spellcooldown_5: -1,
  spellcategory_5: 0,
  spellcategorycooldown_5: -1,
  bonding: 0,
  description: '',
  PageText: 0,
  LanguageID: 0,
  PageMaterial: 0,
  startquest: 0,
  lockid: 0,
  Material: 0,
  sheath: 0,
  RandomProperty: 0,
  RandomSuffix: 0,
  block: 0,
  itemset: 0,
  MaxDurability: 0,
  area: 0,
  Map: 0,
  BagFamily: 0,
  TotemCategory: 0,
  socketColor_1: 0,
  socketContent_1: 0,
  socketColor_2: 0,
  socketContent_2: 0,
  socketColor_3: 0,
  socketContent_3: 0,
  socketBonus: 0,
  GemProperties: 0,
  RequiredDisenchantSkill: -1,
  ArmorDamageModifier: 0,
  ScriptName: '',
  DisenchantID: 0,
  FoodType: 0,
  minMoneyLoot: 0,
  maxMoneyLoot: 0,
  Duration: 0,
  ExtraFlags: 0,
};

